#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

WORKDIR="/usr/share/pwst/gateway/blockchain-lora-wifi-gateway-20260112-094902"

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c '/usr/bin/update-conf.sh; exec /usr/bin/make up'
    procd_set_param env PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin
    procd_set_param cwd "$WORKDIR"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    cd "$WORKDIR" && /usr/bin/make down
}