#!/bin/sh /etc/rc.common

# Start on the latest service
START=99
STOP=1

USE_PROCD=1

start_service() {
	
	# Just to be sure..
	sleep 1
	
    procd_open_instance
    procd_set_param command /usr/bin/healthchek-n-conf.sh
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
